### ISSUE TITLE
Heterogeneous dt and units

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#716] opened 2024-10-18 23:52 UTC
```python
def make_sim():
    hiv = ss.HIV(
        beta = {'random': [ss.beta(0.01)]*2, 'maternal': [ss.beta(0.4), 0]},
        init_prev = ss.bernoulli(0.15),

        dt = 30,
        unit='day'
    )
    pregnancy = ss.Pregnancy(fertility_rate=20)
    death = ss.Deaths(death_rate=10)
    random = ss.RandomNet(n_contacts=ss.poisson(4))
    maternal = ss.MaternalNet()

    sim = ss.Sim(
        dt = 0.5,
        n_agents = n_agents,
        total_pop = 9980999,
        start = sc.date('1990-01-01'),
        dur = 40,
        diseases = [hiv],
        networks = [random, maternal],
        demographics = [pregnancy, death],
    )

    return sim
```

I had expected this to result in HIV taking a 30 day step and everything else taking a 0.5 year time step. Instead, HIV took a 30 year step.

**Comment by cliffckerr** [comment] 2024-11-02 07:09
Duplicate of https://github.com/starsimhub/starsim/issues/676

**Closed by cliffckerr** 2024-11-02 07:09 UTC
Labels: bug
