### ISSUE TITLE
Convert time units away from years

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#418] opened 2024-03-28 00:00 UTC
We currently have timesteps measured in years. To run a simulation in days requires the user to enter `dt=1/365`. The resulting `yearvec` has floating point years that are challenging to convert to datetime for plotting, and this system does not respect actual calendar time (like leap years), which could be relevant for model calibration. Aside from demographic parameters, I suspect most inputs will be in days rather than years. Consider switching to days or a more powerful internal representation like datetime.

Related to #326.

**Comment by cliffckerr** [comment] 2024-04-30 02:27
Duplicate of #326

**Closed by cliffckerr** 2024-04-30 02:27 UTC
Labels: backlog
