### ISSUE TITLE
UID slicing with new API

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#495] opened 2024-05-10 00:37 UTC
```python
self.ti_dead[8262]
nan
self.ti_dead[ss.uids(8262)]
6.75
```

**Comment by cliffckerr** [comment] 2024-05-10 00:46
@daniel-klein This is intended behavior -- the first is indexing the position in the "active" array (i.e. `self.values`, i.e. what you would get with e.g. `self.ti_dead >= sim.ti`), the second is indexing the underlying array (i.e. `self.raw`). The other option would be to disallow int indexing, as e.g. it is disallowed to index with a NumPy array or list.

**Comment by daniel-klein** [comment] 2024-05-14 17:54
Everything should be indexed by UID with either of these syntaxes. If someone wants to see the alive state of the 8262th agent, they should have some other api/syntax like ```self.ti_dead.values[8262]```

**Comment by cliffckerr** [comment] 2024-05-28 13:00
Closed by #527

**Closed by cliffckerr** 2024-05-28 13:00 UTC
Labels: bug, MVP, quick
