### ISSUE TITLE
Refactor par_dists

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#354] opened 2024-03-02 19:17 UTC
Good discussion on slack resulting in a few options:

1. From @RomeshA:

```python
pars = ss.omergeleft(pars,
    dur_inf = 1,
    init_prev = 0.1,
    p_death = 0.2,
    beta = None,
)
        
pars.dur_inf = ss.make_dist(pars.dur_inf, ss.lognorm)
pars.init_prev = ss.make_dist(pars.init_prev, ss.bernoulli)
pars.p_death = ss.make_dist(pars.p_death, ss.bernoulli)
```

2. From @cliffckerr:
```python
pars = ss.omergeleft(pars,
    dur_inf = {'lognorm':1},
    init_prev = {'bernoulli':0.1},
    p_death = {'bernoulli':0.2},
    beta = None,
)
```

3. From me:
```python
pars = ss.omergeleft(pars,
    dur_inf = sps.lognorm(s=1)
    init_prev = 0.1, # Do not specify a distribution for Bernoulli, even though we will convert to a ScipyDistribution under the hood (in part to enable CRN and callable parameters).
    p_death = 0.2,
    beta = None,
)
```
```python
ss.set_distpars(disease.pars.dur_inf, s=5)
disease.pars.dur_inf.kwds['s'] = 5
disease.pars.dur_inf = sps.norm(loc=10)
```

**Comment by cliffckerr** [comment] 2024-03-12 01:19
Duplicate of https://github.com/starsimhub/starsim/issues/292

**Comment by kaa2102** [comment] 2024-04-19 18:35
`par_dists` usage in Starsim codebase

demographics.py
lines 115, 139, 153, 248, 273

network.py
lines 435, 530, 539, 550

modules.py
lines 74, 82

products.py
lines 143, 145,146

disease/cholera.py
lines 17, 42, 53

disease/ebola.py
lines 16, 38, 51

diseases/hiv.py
lines 14, 34, 39

diseases/gonorrhea.py
lines 13, 32, 39

disease/measles.py
lines 16, 30, 37

disease/sir.py
lines 21, 29, 35, 101, 119, 120, 181

docs/tutorials/tut_buildsim.ipynb*
line 106

**Comment by cliffckerr** [comment] 2024-04-29 23:19
Or we could do this:
```py
self.pars = dict(
    dur_inf = ss.lognorm_ex(1)
    init_prev = ss.bernoulli(0.1),
    p_death = ss.bernoulli(0.2),
    beta = None,
)
self.pars.update(**kwargs) # automatically merges with correct structure
```

**Comment by cliffckerr** [comment] 2024-04-30 02:35
Subsumed into #301

**Closed by cliffckerr** 2024-04-30 02:35 UTC
Labels: question, refactor, APHRC
